- name: RHEL | Install {{ _firewall_name }}
  yum:
    name: "{{ _firewall_name }}"
    state: latest

- name: RHEL | Set firewall template name (XenServer)
  set_fact:
    _firewall_template: "iptables-{{ ansible_facts.distribution }}"
  when: ansible_facts.distribution == 'XenServer'
  tags:
    - firewall
    - firewall_config
