- name: DEBIAN | Install iptables
  apt:
    name: iptables
    state: latest
  tags:
    - firewall

- name: DEBIAN | Copy iptables load script
  template:
    src: iptablesload.j2
    dest: /etc/if-pre-up.d/iptablesload
    owner: root
    group: root
    mode: '0700'
  tags:
    - firewall
    - firewall_config
