Vagrant.configure(2) do |config|

  # CentOS 6
  config.vm.define "firewall-el6" do |centos6|
    centos6.vm.box = "samdoran/centos6"
    centos6.vm.hostname = "firewall-centos6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "firewall-el6"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # CentOS 7
  config.vm.define "firewall-el7" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "firewall-centos7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "firewall-el7"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # Ubuntu 14.04
  config.vm.define "firewall-ub14" do |ub14|
    ub14.vm.box = "geerlingguy/ubuntu1404"
    ub14.vm.hostname = "firewall-ub14"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "firewall-ub14"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # Ubuntu 16.04
  config.vm.define "firewall-ub16" do |ub16|
    ub16.vm.box = "geerlingguy/ubuntu1604"
    ub16.vm.hostname = "firewall-ub16"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "firewall-ub16"
      vbox.cpus = 1
      vbox.memory = 256
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

end
